# Generated by Django 3.1.2 on 2020-11-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20201012_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Major_requirement',
            new_name='MajorRequirement',
        ),
    ]
